@baseUrl = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMDAwMDAwMDAwMCIsImlhdCI6MTc1MDcwNjQ2MSwiZXhwIjoxNzUwNzA4MjYxfQ.39fT471AfhuSxMOS8L14rkOTo1jDxzPWQdtGsMVPXzU

### Welcome endpoint (GET)
GET {{baseUrl}}/auth/welcome

###
# Add user 1
POST {{baseUrl}}/auth/addNewUser
Content-Type: application/json

{
  "cpf": "12345678900",
  "name": "João Silva",
  "password": "123456",
  "dataNascimento": "1990-01-01"
}

###
# Add user 2
POST {{baseUrl}}/auth/addNewUser
Content-Type: application/json

{
  "name": "Maria Oliveira",
  "cpf": "09876543211",
  "password": "123456",
  "dataNascimento": "1990-02-02"
}

### login user 1
# @name login
POST http://localhost:8080/auth/generateToken
Content-Type: application/json

{
  "cpf": "12345678900",
  "password": "123456"
}

### login user 1
# @name login
POST http://localhost:8080/auth/generateToken
Content-Type: application/json

{
  "cpf": "12345678900",
  "password": "123456"
}

### login AMDIN
# @name login
POST http://localhost:8080/auth/generateToken
Content-Type: application/json

{
  "cpf": "00000000000",
  "password": "123456"
}

###
# Protected endpoint example (GET) - uses the saved token
GET http://localhost:8080/bank/status
Authorization: Bearer {{token}}

###
# consultar denuncias feitas ao usuario
GET http://localhost:8080/bank/denuncias
Authorization: Bearer {{token}}

### 
# See account status
GET http://localhost:8080/bank/consultar
Authorization: Bearer {{token}}

### 
# See account extract
GET http://localhost:8080/bank/extrato
Authorization: Bearer {{token}}

###
#denunciar
POST http://localhost:8080/bank/denunciar
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "codigoTransacao": "TX123456",
  "motivo": "Transação suspeita",
  "detalhes": "O valor transferido não foi combinado.",
  "cpfDenunciado": "09876543211"
}

###
#Depositar saldo em conta
POST http://localhost:8080/bank/depositar
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "cpfDestino": "12059930456",
  "valor": 100.00
}

###
#transferir
POST http://localhost:8080/bank/transferir
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "cpfDestino": "09876543211",
  "valor": 50.00
}


### ADMIN - Listar transações
GET http://localhost:8080/admin/todos-extratos
Authorization: Bearer {{token}}

### ADMIN - Listar denuncias
GET http://localhost:8080/admin/todas-denuncias
Authorization: Bearer {{token}}

### ADMIN - aprovar denuncia
POST http://localhost:8080/admin/atualizar-denuncia?denunciaId=1&status=aprovada
Authorization: Bearer {{token}}
