@baseUrl = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwMCIsImlhdCI6MTc1MDY4NTY3MiwiZXhwIjoxNzUwNjg3NDcyfQ.6-Dh-koE4FrNIITcV7xzoBklnVChNV-cIUGsWJc5Mxc

### Welcome endpoint (GET)
GET {{baseUrl}}/auth/welcome

###
# Add user 1
POST {{baseUrl}}/auth/addNewUser
Content-Type: application/json

{
  "cpf": "12345678900",
  "password": "123456",
  "dataNascimento": "1990-01-01"
}

###
# Add user 2
POST {{baseUrl}}/auth/addNewUser
Content-Type: application/json

{
  "cpf": "09876543211",
  "password": "123456",
  "dataNascimento": "1990-02-02"
}

###
# @name login
POST http://localhost:8080/auth/generateToken
Content-Type: application/json

{
  "cpf": "12345678900",
  "password": "123456"
}

###
# Protected endpoint example (GET) - uses the saved token
GET http://localhost:8080/bank/status
Authorization: Bearer {{token}}


### 
# See account status
GET http://localhost:8080/bank/consultar
Authorization: Bearer {{token}}

### 
# See account extract
GET http://localhost:8080/bank/extrato
Authorization: Bearer {{token}}

###
#denunciar
POST http://localhost:8080/bank/denunciar
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "codigoTransacao": "TX123456",
  "motivo": "Transação suspeita",
  "detalhes": "O valor transferido não foi combinado.",
  "cpfDenunciante": "12345678900",
  "cpfDenunciado": "09876543211"
}

###
#Depositar saldo em conta
POST http://localhost:8080/bank/depositar
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "cpfDestino": "12345678900",
  "valor": 100.00
}

###
#transferir
POST http://localhost:8080/bank/transferir
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "cpfRemetente": "12345678900",
  "cpfDestino": "09876543211",
  "valor": 50.00
}