@baseUrl = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZUBleGVtcGxvLmNvbSIsImlhdCI6MTc1MDY3OTgyOCwiZXhwIjoxNzUwNjgxNjI4fQ.9fkoZ0YV_yzRYZJJIcD72ynrHRbsI9Yy4R6bpMwsFt8

### Welcome endpoint (GET)
GET {{baseUrl}}/auth/welcome

###

# Add new user (POST)
POST {{baseUrl}}/auth/addNewUser
Content-Type: application/json

{
  "email": "teste@exemplo.com",
  "password": "123456",
  "roles": "ROLE_USER"
}

###
# @name login
POST http://localhost:8080/auth/generateToken
Content-Type: application/json

{
  "username": "teste@exemplo.com",
  "password": "123456"
}

###
# Protected endpoint example (GET) - uses the saved token
GET http://localhost:8080/bank/status
Authorization: Bearer {{token}}


### 
# See account status
GET http://localhost:8080/bank/consultar
Authorization: Bearer {{token}}